# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :build do
#       increment_version_code(
#                 gradle_file_path: "../android/app/build.gradle",
#                 #ext_constant_name: "test"
#                 #app_folder_name:"app"
#           )
      gradle(task: 'clean')
      gradle(task: 'assemble', build_type: 'Release')
      end

#54366@teml.net - staff
#sconde2003@gmail.com - owner
#54367@teml.net - player


  lane :distribute do
   build
   firebase_app_distribution(
     #firebase login:ci to get firebase_cli_token
     app: "1:576181436121:android:22cf1795e0bb5f514bc8c8",
     #testers: "sconde2003@gmail.com, adawodu27@gmail.com, forikujuni92@gmail.com",
     groups: "sona-team",
     firebase_cli_token: "1//03eIEEiG-1lWgCgYIARAAGAMSNwF-L9IraweTeCC7hwoI8FW9tigQZRkG6yAx6Uyb0kKBZTbnWUllkC09z0HnGqRne9S3SrdkSlQ",
     release_notes: "Version 2\nPlayers and Staff (coach & manager) login fix",
     apk_path: "/Users/condelab/AndroidStudioProjects/SonalysisRevamp/build/app/outputs/flutter-apk/app-release.apk")
end
end
